[selectionTool] fix IndexError when draggin last offcurve in contour while SHIFT pressed
We need to modulo the offsetted index, else this happens:

Traceback (most recent call last):
  File "trufont/Lib/trufont/controls/glyphCanvasView.py", line 404, in mouseMoveEvent
    self._redirectEvent(event, self._currentTool.mouseMoveEvent, True)
  File "trufont/Lib/trufont/controls/glyphCanvasView.py", line 499, in _redirectEvent
    callback(event)
  File "trufont/Lib/trufont/drawingTools/selectionTool.py", line 431, in mouseMoveEvent
    p__ = c[i+d]
  File "/usr/local/var/pyenv/versions/3.6.1/envs/trufont361/lib/python3.6/site-packages/defcon/objects/contour.py", line 229, in __getitem__
    return self._points.__getitem__(index)
IndexError: list index out of range